# Generated by Django 3.1.7 on 2021-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelu', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
